services:
  api:
    image: golang:1.24.1-bullseye
    ports:
      - "${PORT}:${PORT}"
    working_dir: /app
    volumes:
      - ./cmd:/app/cmd
      - ./internal:/app/internal
      - ./go.mod:/app/go.mod
      - ./go.sum:/app/go.sum
      - ./.env:/app/.env
    command: >
      sh -c "
      go mod download &&
      go build -a -installsuffix cgo -o /bin/api cmd/api/*.go &&
      chmod +x /bin/api &&
      /bin/api"
    restart: unless-stopped
